### ISSUE TITLE
Preset 0 is always on 

### ISSUE THREAD

**Issue by Krocko** [bbriatte/homebridge-soundtouch-platform#1]
Hello. Thank you very much for this great Plugin!
I have waiting so long for this. 
I have a SoundTouch 300 and the preset 0 is the TV input (like you discribed in the readme). But it is always on. If i Switch the preset off, it goes back to on.

**Comment by bbriatte** [comment]
Hello @Krocko,

Yes i have the same problem. I will check it this week

**Comment by Krocko** [comment]
Problem solved with v.1.0.2

**Comment by Krocko** [comment]
Now with v.1.0.2 the TV preset is off if the device is off.
But if i switch on e.g. preset 1, the switch from preset 1 goes on then off an the switch from the tv input goes on.
Also on a second soundtouch device the switches for the presets now always off.


I checked again. The problem is only on presets with playlist.
Preset 1 til preset 4 are radio stations from tune in. They are working.
Preset 5 and preset 6 are playlists from a nas. If i switch this presets on, the toggle goes off immediately.

This problem is with v.1.0.1 and v.1.0.2

**Comment by Nastras** [comment]
@Krocko 
Could you publish your config in Issue https://github.com/bbriatte/homebridge-soundtouch-platform/issues/3 I think the error is there. Which version of the plugin do you currently have?

Thank you.

**Comment by Krocko** [comment]
Sorry, i am back on the other soundtouch plugin. 
Will wait for @bbriatte to fix the issue. 
Maybe you can test with v.1.0.2? 
Config.json i used, was this:
https://github.com/bbriatte/homebridge-soundtouch-platform/commit/87b8701ddaeb652a43948f70a9580d655af2aeb6#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by Nastras** [comment]
Yes, the example configs I've tried all Possible variant. Unfortunately, it crashes with the bug from Issue # 3. Therefore, I thought that I probably have a bug in my config and can compare this with yours.

Version 1.0.2 is not offered to me at npm. Only version 1.0.0.

**Comment by bbriatte** [comment]
I change the name of the npm package @Krocko, now it's ` homebridge-soundtouch-platform@1.0.1`
This transform the accessory into a platform, it's easier to register devices.
Now, normally you need just to write in your config.json file in the `platforms` key :
```
{
    "platform": "SoundTouchPlatform",
    "name": "SoundTouch",
    "discoverAllAccessories": true
  }
```

**Comment by Krocko** [comment]
Oh nice!
With this config all devices are discovered?
Also all presets are visible?

**Comment by bbriatte** [comment]
yes & yes :)

**Comment by Krocko** [comment]
It is working now
