### ISSUE TITLE
Presets not visible

### ISSUE THREAD

**Issue by Spy-1** [bbriatte/homebridge-soundtouch-platform#12]
I have the problem that not all presets are displayed in Homekit.
Only Preset 4 is displayed. All other presets are not visible.
My config.json:
{
            "platform": "SoundTouchPlatform",
            "name": "SoundTouch",
            "discoverAllAccessories": true,
            "global": {
                "sources": [
                    {
                        "source": "QPLAY",
                        "enabled": false
                    },
                    {
                        "source": "AUX",
                        "enabled": false
                    }
                ]
            }
        },

**Comment by jeffvautin** [comment]
I have this same issue with one of my two speakers. Strange. It's also preset 4 for me that's present on the one device.

**Comment by mishakim** [comment]
I have the same issue with manually configured speaker, with only one of two. They both have the same preset array as below, though the non-working one (shown) has some presets disabled. Only #2 shows up, regardless of whether the others are enabled or disabled. For the other speaker, all six showed up when I only defined two, and all took the names I gave them when I defined all six

{
                    "name": "Girls Room Speaker",
                    "room": "Girls Room",
                    "volume": {
                        "unmuteValue": 40,
                        "maxValue": 80,
                        "mode": "lightbulb"
                    },
                    "presets": [
                        {
                            "name": "TMBG",
                            "index": 1
                        },
                        {
                            "name": "Campfire",
                            "index": 2
                        },
                        {
                            "name": "Beatles",
                            "index": 3
                        },
                        {
                            "name": "Classical",
                            "index": 4
                        },
                        {
                            "name": "Classical Focus",
                            "index": 5,
                            "enabled": false
                        },
                        {
                            "name": "WBUR",
                            "index": 6
                        }
                    ],
                    "sources": [
                        {
                            "source": "BLUETOOTH",
                            "name": "Bluetooth",
                            "enabled": false
                        },
                        {
                            "source": "AUX",
                            "name": "Receiver",
                            "enabled": false
                        }
                    ]
                }

**Comment by mishakim** [comment]
This resolved itself after another restart ahead of updating homebridge - presets are now visible as configured
