### ISSUE TITLE
verbose config option is not working

### ISSUE THREAD

**Issue by bachandi** [bbriatte/homebridge-soundtouch-platform#20]
The verbose config option does not work.
The `typeof verbose` is `string` and not boolean so all these `===` comparisons with a boolean value fail always.

https://github.com/bbriatte/homebridge-soundtouch-platform/blob/b8c919f589524dc0191c8ca70318f4c3afe71a62/src/sound-touch-device.ts#L62

**Comment by bachandi** [comment]
Just due to typo in config file... there is a difference between `"true"` and `true` in JS:D

**Comment by bbriatte** [comment]
Show me your config file

**Comment by bbriatte** [comment]
Ahah ok !
