### ISSUE TITLE
Decrease log output on non verbose mode?

### ISSUE THREAD

**Issue by bachandi** [bbriatte/homebridge-soundtouch-platform#21]
Would it be possible to decrease the log output in non verbose mode? Otherwise after some time the log is pretty cluttered with output with `Current volume` and `Is on`/`Is off` lines. 
If one like this output there is still the verbose true config option. I think there would be no need for a second verbosity variable. What do you think on this?

**Comment by bbriatte** [comment]
Will be in the next npm release #1.4.0
