### ISSUE TITLE
Filling log after upgrade to Homebridge 1.3.0

### ISSUE THREAD

**Issue by AndersKlinting** [bbriatte/homebridge-soundtouch-platform#32]
After upgrade and restart the following gets logged  every two seconds (the second message only in debug mode):

[homebridge-soundtouch-platform] This plugin generated a warning from the characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response! See https://git.io/JtMGR for more info.

[homebridge-soundtouch-platform] Error: 
    at Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2063:79)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1618:22
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at /usr/local/lib/node_modules/homebridge-soundtouch-platform/node_modules/homebridge-base-platform/src/callback.ts:17:34

How can I prevent this from happening?

**Comment by spikester2391** [comment]
I have now upgraded to 1.3.2 and the error noted by @AndersKlinting persists.  I see the same:

[05/03/2021, 11:24:52] [homebridge-soundtouch-platform] This plugin generated a warning from the characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.

While annoying, there doesn't seem to be any other effect.

**Comment by mishakim** [comment]
I'm not seeing that error, but I'm getting this on a fairly regular basis:
`[3/7/2021, 7:51:06 AM] [homebridge-soundtouch-platform] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://git.io/JtMGR for more info.`

**Comment by spikester2391** [comment]
The problem appears to be resolved for me, at least cosmetically, through installation of Homebridge 1.3.3.

**Comment by AndersKlinting** [comment]
I see the same as @spikester2391 after upgrade if homebridge to 1.3.3,  so I close this issue
