### ISSUE TITLE
Feature Request: Turn on volume set

### ISSUE THREAD

**Issue by Nastras** [bbriatte/homebridge-soundtouch-platform#5]
Is it possible in the config to set a volume when the loudspeaker is switched on?

**Comment by Nastras** [comment]
https://github.com/bbriatte/homebridge-soundtouch-platform/issues/3#issuecomment-489419144

**Comment by bbriatte** [comment]
adding with v1.1.1 
key: onVolume

**Comment by Nastras** [comment]
Just tested, works great.

Many Thanks!!!
